#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define CH32V003           1

#define RANDOM_STRENGTH    2

#define FUNCONF_USE_DEBUGPRINTF 1
#define FUNCONF_USE_UARTPRINTF  0
#define FUNCONF_SYSTICK_USE_HCLK 1

#endif

